export const sportsData = [
  {
    id: 1,
    name: "NBA",
    slug: "nba",
    icon: "🏀",
    bookmakers: [
      { id: "bet365", name: "bet365" },
      { id: "pinnacle", name: "PINNACLE" },
      { id: "betvictor", name: "BETVICTOR" },
      { id: "williamhill", name: "William Hill" },
      { id: "888", name: "888" },
      { id: "betway", name: "betway" },
    ],
    games: [
      {
        id: 1,
        time: "19:00",
        team1: {
          name: "Washington Wizards",
          abbr: "WAS",
          open: "+3.0",
          odds: [
            { bookmaker: "bet365", value: "+3.0", american: "1.91", highlighted: false },
            { bookmaker: "pinnacle", value: "+3.0", american: "1.94", highlighted: false },
            { bookmaker: "betvictor", value: "+3.5", american: "1.80", highlighted: false },
            { bookmaker: "williamhill", value: "+3.0", american: "1.91", highlighted: false },
            { bookmaker: "888", value: "", american: "", highlighted: false },
            { bookmaker: "betway", value: "+2.5", american: "1.95", highlighted: true },
          ],
        },
        team2: {
          name: "Philadelphia 76ers",
          abbr: "PHI",
          open: "-3.0",
          odds: [
            { bookmaker: "bet365", value: "-3.0", american: "1.91", highlighted: false },
            { bookmaker: "pinnacle", value: "-3.0", american: "1.96", highlighted: false },
            { bookmaker: "betvictor", value: "-3.5", american: "1.95", highlighted: false },
            { bookmaker: "williamhill", value: "-3.0", american: "1.91", highlighted: false },
            { bookmaker: "888", value: "", american: "", highlighted: false },
            { bookmaker: "betway", value: "-2.5", american: "1.87", highlighted: false },
          ],
        },
      },
      {
        id: 2,
        time: "19:30",
        team1: {
          name: "Los Angeles Lakers",
          abbr: "LAL",
          open: "-1.0",
          odds: [
            { bookmaker: "bet365", value: "-1.0", american: "1.95", highlighted: false },
            { bookmaker: "pinnacle", value: "+1.0", american: "1.95", highlighted: true },
            { bookmaker: "betvictor", value: "-1.5", american: "1.95", highlighted: false },
            { bookmaker: "williamhill", value: "-1.0", american: "1.91", highlighted: false },
            { bookmaker: "888", value: "", american: "", highlighted: false },
            { bookmaker: "betway", value: "-1.5", american: "1.95", highlighted: false },
          ],
        },
        team2: {
          name: "Indiana Pacers",
          abbr: "IND",
          open: "+1.0",
          odds: [
            { bookmaker: "bet365", value: "+1.0", american: "1.87", highlighted: false },
            { bookmaker: "pinnacle", value: "-1.0", american: "1.95", highlighted: false },
            { bookmaker: "betvictor", value: "+1.5", american: "1.80", highlighted: false },
            { bookmaker: "williamhill", value: "+1.0", american: "1.91", highlighted: false },
            { bookmaker: "888", value: "", american: "", highlighted: false },
            { bookmaker: "betway", value: "+1.5", american: "1.87", highlighted: true },
          ],
        },
      },
      {
        id: 3,
        time: "19:30",
        team1: {
          name: "Los Angeles Clippers",
          abbr: "LAC",
          open: "-1.5",
          odds: [
            { bookmaker: "bet365", value: "-3.0", american: "1.91", highlighted: false },
            { bookmaker: "pinnacle", value: "-3.0", american: "1.93", highlighted: false },
            { bookmaker: "betvictor", value: "-2.5", american: "1.80", highlighted: false },
            { bookmaker: "williamhill", value: "-3.0", american: "1.91", highlighted: false },
            { bookmaker: "888", value: "", american: "", highlighted: false },
            { bookmaker: "betway", value: "-2.5", american: "1.87", highlighted: true },
          ],
        },
        team2: {
          name: "New York Knicks",
          abbr: "NY",
          open: "+1.5",
          odds: [
            { bookmaker: "bet365", value: "+3.0", american: "1.91", highlighted: false },
            { bookmaker: "pinnacle", value: "+3.0", american: "1.97", highlighted: false },
            { bookmaker: "betvictor", value: "+2.5", american: "1.95", highlighted: false },
            { bookmaker: "williamhill", value: "+3.0", american: "1.91", highlighted: false },
            { bookmaker: "888", value: "", american: "", highlighted: false },
            { bookmaker: "betway", value: "+2.5", american: "1.95", highlighted: true },
          ],
        },
      },
    ],
  },
  {
    id: 2,
    name: "NCAAB",
    slug: "ncaab",
    icon: "🏀",
    bookmakers: [
      { id: "bet365", name: "bet365" },
      { id: "pinnacle", name: "PINNACLE" },
      { id: "betvictor", name: "BETVICTOR" },
      { id: "williamhill", name: "William Hill" },
      { id: "888", name: "888" },
      { id: "betway", name: "betway" },
    ],
    games: [
      {
        id: 1,
        time: "19:00",
        team1: {
          name: "Duke Blue Devils",
          abbr: "DUKE",
          open: "-5.5",
          odds: [
            { bookmaker: "bet365", value: "-5.5", american: "1.91", highlighted: false },
            { bookmaker: "pinnacle", value: "-5.5", american: "1.94", highlighted: false },
            { bookmaker: "betvictor", value: "-5.5", american: "1.90", highlighted: false },
            { bookmaker: "williamhill", value: "-5.5", american: "1.91", highlighted: false },
            { bookmaker: "888", value: "-5.5", american: "1.91", highlighted: false },
            { bookmaker: "betway", value: "-5.5", american: "1.91", highlighted: false },
          ],
        },
        team2: {
          name: "North Carolina Tar Heels",
          abbr: "UNC",
          open: "+5.5",
          odds: [
            { bookmaker: "bet365", value: "+5.5", american: "1.91", highlighted: false },
            { bookmaker: "pinnacle", value: "+5.5", american: "1.94", highlighted: false },
            { bookmaker: "betvictor", value: "+5.5", american: "1.90", highlighted: false },
            { bookmaker: "williamhill", value: "+5.5", american: "1.91", highlighted: false },
            { bookmaker: "888", value: "+5.5", american: "1.91", highlighted: false },
            { bookmaker: "betway", value: "+5.5", american: "1.91", highlighted: false },
          ],
        },
      },
    ],
  },
  {
    id: 3,
    name: "NFL",
    slug: "nfl",
    icon: "🏈",
    bookmakers: [
      { id: "bet365", name: "bet365" },
      { id: "pinnacle", name: "PINNACLE" },
      { id: "williamhill", name: "William Hill" },
      { id: "betway", name: "betway" },
    ],
    games: [
      {
        id: 1,
        time: "20:15",
        team1: {
          name: "Kansas City Chiefs",
          abbr: "KC",
          open: "-3.0",
          odds: [
            { bookmaker: "bet365", value: "-3.0", american: "1.91", highlighted: false },
            { bookmaker: "pinnacle", value: "-3.0", american: "1.94", highlighted: false },
            { bookmaker: "williamhill", value: "-3.0", american: "1.91", highlighted: false },
            { bookmaker: "betway", value: "-3.0", american: "1.91", highlighted: false },
          ],
        },
        team2: {
          name: "Baltimore Ravens",
          abbr: "BAL",
          open: "+3.0",
          odds: [
            { bookmaker: "bet365", value: "+3.0", american: "1.91", highlighted: false },
            { bookmaker: "pinnacle", value: "+3.0", american: "1.94", highlighted: false },
            { bookmaker: "williamhill", value: "+3.0", american: "1.91", highlighted: false },
            { bookmaker: "betway", value: "+3.0", american: "1.91", highlighted: false },
          ],
        },
      },
    ],
  },
]

